/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 159OA - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.post_api_user_login': ['POST', '/api/user/login'],
  'general.post_api_attendance_index': ['POST', '/api/attendance/index'],
  'user.get_test_user': ['GET', '/test/user'],
  'general.post_api_attendance_clock': ['POST', '/api/attendance/clock'],
  'general.get_api_attendance_monthlystats': ['GET', '/api/attendance/monthlyStats'],
  'general.get_api_attendance_userinfo': ['GET', '/api/attendance/userInfo']
};
