/* tslint:disable */
/* eslint-disable */
/**
 * 159OA - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [POST] 登录
       *
       * **path:** /api/user/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   account?: string
       *   password?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   time: string
       *   data: {
       *     userinfo: {
       *       id: number
       *       username: string
       *       nickname: string
       *       avatar: string
       *       mobile: string
       *       token: string
       *       user_id: number
       *       createtime: number
       *       expiretime: number
       *       expires_in: number
       *     }
       *   }
       * }
       * ```
       */
      post_api_user_login<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          time: string;
          data: {
            userinfo: {
              id: number;
              username: string;
              nickname: string;
              avatar: string;
              mobile: string;
              token: string;
              user_id: number;
              createtime: number;
              expiretime: number;
              expires_in: number;
            };
          };
        }> & {
          data: {
            account?: string;
            password?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          time: string;
          data: {
            userinfo: {
              id: number;
              username: string;
              nickname: string;
              avatar: string;
              mobile: string;
              token: string;
              user_id: number;
              createtime: number;
              expiretime: number;
              expires_in: number;
            };
          };
        },
        'general.post_api_user_login',
        Config
      >;
      /**
       * ---
       *
       * [GET] 签到（开发中）
       *
       * **path:** /api/attendance/index
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_api_attendance_index<Config extends Alova2MethodConfig<object>>(
        config?: Config
      ): Alova2Method<object, 'general.get_api_attendance_index', Config>;
    };
    user: {
      /**
       * ---
       *
       * [GET] 测试接口
       *
       * **path:** /test/user
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   aaa: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_test_user<
        Config extends Alova2MethodConfig<object> & {
          data: {
            aaa: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'user.get_test_user', Config>;
    };
  }

  var Apis: Apis;
}
