/* tslint:disable */
/* eslint-disable */
/**
 * 159OA - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [POST] 登录
       *
       * **path:** /api/user/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   account?: string
       *   password?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   time: string
       *   data: {
       *     userinfo: {
       *       id: number
       *       username: string
       *       nickname: string
       *       avatar: string
       *       mobile: string
       *       token: string
       *       user_id: number
       *       createtime: number
       *       expiretime: number
       *       expires_in: number
       *     }
       *   }
       * }
       * ```
       */
      post_api_user_login<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          time: string;
          data: {
            userinfo: {
              id: number;
              username: string;
              nickname: string;
              avatar: string;
              mobile: string;
              token: string;
              user_id: number;
              createtime: number;
              expiretime: number;
              expires_in: number;
            };
          };
        }> & {
          data: {
            account?: string;
            password?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          time: string;
          data: {
            userinfo: {
              id: number;
              username: string;
              nickname: string;
              avatar: string;
              mobile: string;
              token: string;
              user_id: number;
              createtime: number;
              expiretime: number;
              expires_in: number;
            };
          };
        },
        'general.post_api_user_login',
        Config
      >;
      /**
       * ---
       *
       * [POST] 打卡首页
       *
       * **path:** /api/attendance/index
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   lng?: string
       *   lat?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_api_attendance_index<
        Config extends Alova2MethodConfig<object> & {
          data: {
            lng?: string;
            lat?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_api_attendance_index', Config>;
      /**
       * ---
       *
       * [POST] 打卡
       *
       * **path:** /api/attendance/clock
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 打卡经度
       *   lng?: string
       *   // 打卡纬度
       *   lat?: string
       *   // 打卡地点
       *   location?: string
       *   // 是否外出打卡 0=否，1=是
       *   is_outing?: string
       *   // 外出原因
       *   outing_reason?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      post_api_attendance_clock<
        Config extends Alova2MethodConfig<object> & {
          data: {
            /**
             * 打卡经度
             */
            lng?: string;
            /**
             * 打卡纬度
             */
            lat?: string;
            /**
             * 打卡地点
             */
            location?: string;
            /**
             * 是否外出打卡 0=否，1=是
             */
            is_outing?: string;
            /**
             * 外出原因
             */
            outing_reason?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<object, 'general.post_api_attendance_clock', Config>;
      /**
       * ---
       *
       * [GET] 考勤统计
       *
       * **path:** /api/attendance/monthlyStats
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   year?: string
       *   month?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: number
       *   msg: string
       *   time: string
       *   data: {
       *     year: number
       *     month: number
       *     // [items] start
       *     // [items] end
       *     calendar: Array<{
       *       date: string
       *       day: number
       *       status: string
       *       clock_in: string
       *       clock_out: string
       *       work_hours: number
       *       in_status: string
       *       out_status: string
       *     }>
       *     total_work_hours: number
       *     normal_days: number
       *     abnormal_days: number
       *     total_days: string
       *   }
       * }
       * ```
       */
      get_api_attendance_monthlystats<
        Config extends Alova2MethodConfig<{
          code: number;
          msg: string;
          time: string;
          data: {
            year: number;
            month: number;
            calendar: Array<{
              date: string;
              day: number;
              status: string;
              clock_in: string;
              clock_out: string;
              work_hours: number;
              in_status: string;
              out_status: string;
            }>;
            total_work_hours: number;
            normal_days: number;
            abnormal_days: number;
            total_days: string;
          };
        }> & {
          params: {
            year?: string;
            month?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<
        {
          code: number;
          msg: string;
          time: string;
          data: {
            year: number;
            month: number;
            calendar: Array<{
              date: string;
              day: number;
              status: string;
              clock_in: string;
              clock_out: string;
              work_hours: number;
              in_status: string;
              out_status: string;
            }>;
            total_work_hours: number;
            normal_days: number;
            abnormal_days: number;
            total_days: string;
          };
        },
        'general.get_api_attendance_monthlystats',
        Config
      >;
    };
    user: {
      /**
       * ---
       *
       * [GET] 测试接口
       *
       * **path:** /test/user
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = object
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = object
       * ```
       */
      get_test_user<
        Config extends Alova2MethodConfig<object> & {
          data: object;
        }
      >(
        config: Config
      ): Alova2Method<object, 'user.get_test_user', Config>;
    };
  }

  var Apis: Apis;
}
